#!/bin/bash
# ============================================================
# compositors/niri
# ============================================================

COMPOSITOR_LABEL="Niri (Intel/AMD Integrated)"

start_niri() {
    clear

    # Important for Generic Wayland/Integrated GPU
    export ELECTRON_OZONE_PLATFORM_HINT=auto

    # Starts the Wayland session on the integrated GPU.
    niri-session -l

    return 0
}
